apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: {{ .Chart.Name }}-client
        image: monasamir/client:b${BUILD_NUMBER} 
        ports:
        - containerPort: 3000 