apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: server 
  template:
    metadata:
      labels:
        app: server 
    spec:
      containers:
      - name: {{ .Chart.Name }}-server
        image: monasamir/server:b${BUILD_NUMBER} 
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-uri
              key: MONGO_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jw
              key: JWT_SECRET

